#!/usr/bin/env ruby
rootPath = "/Volumes/MrData/Projects/log"
filePath = rootPath+"/"+Time.now.strftime("%Y-%b").downcase+".yml"

puts filePath

if !File.exists?(filePath)
  open(filePath, 'w') do |f|
    f << %(title: Log for #{Time.now.strftime('%Y-%B')}
created_at: #{Time.now.to_s}
kind: log
data:)
  end
end

open(filePath, 'a') do |f|
  f << %(
-
  time: #{Time.now.to_s}
  topic: none
  url: https://github.com/attilam
  media: http://rotonde.attilam.com/media/img.jpg
  data:
    - focus: 0.5
  text: |
    BLAH
)
end

system(ENV['EDITOR']+' '+filePath)
